Added editorConfig for backend and prettier for frontEnd,
Dax0s/2024-fall-psi pull request #6
Opened 2024-09-16 19:28 UTC by AiniusG

- added back end formating with editorconfig (template from https://github.com/dotnet/aspnetcore/blob/main/.editorconfig)
- added front end formating with prettier 
- updated read me to show how to use these formatting command

2024-09-16 19:39 UTC, soixante-neuf approved these changes
readMe.md --> README.md būtų gal kažkiek geriau, bet šiaip not a big deal.

2024-09-17 06:27 UTC, AtomicTacoDev commented on readMe.md
> +- To format frontend: in "2024-fall-psi\frotnend" run "npm run format"
Typo "frotnend"

2024-09-17 06:30 UTC, AtomicTacoDev requested changes
Istaisyt readme typo ir good

2024-09-17 09:50 UTC, Dax0s approved these changes

2024-09-17 10:02 UTC, AtomicTacoDev approved these changes

2024-09-17 10:04 UTC, merged