4 aidas  reaction button
Dax0s/2024-fall-psi pull request #7
Opened 2024-09-17 14:41 UTC by soixante-neuf

2024-09-18 14:37 UTC, Dax0s requested changes

2024-09-18 14:37 UTC, Dax0s commented on backend/backend/Controllers/ReactionTimeController.cs
> +        const int MILLISECONDS_IN_SECOND = 1000;
Man atrodo metoduose cont kintamuosius reiktu ne vien didziosiomis rasyti.
Rider rekomendacija: Name 'MILLISECONDS_IN_SECOND' does not match rule 'Local constants'. Suggested name is 'millisecondsInSecond'.

2024-09-18 14:37 UTC, Dax0s commented on backend/backend/Controllers/ReactionTimeController.cs
> +        const int MIN_WAIT = 2 * MILLISECONDS_IN_SECOND;
Tas pats cia

2024-09-18 14:37 UTC, Dax0s commented on backend/backend/Controllers/ReactionTimeController.cs
> +        const int MAX_WAIT = 5 * MILLISECONDS_IN_SECOND;
Ir cia

2024-09-18 14:37 UTC, Dax0s commented on frontend/src/ReactionButton.tsx
Reiktu sita perdaryti i functional komponenta, react klases outdated
Ract patys tai siulo: https://react.dev/reference/react/Component

2024-09-18 14:37 UTC, Dax0s commented on frontend/src/ReactionButton.tsx
> +        this.clickOnOff();
Reikia await

2024-09-18 14:37 UTC, Dax0s commented on frontend/src/ReactionButton.tsx
> +        ? 'Reaction time: ' + this.state.reactionTime + ' ms'
```suggestion
        ? 'Reaction time: ' + Math.floor(this.state.reactionTime) + ' ms'
```

2024-09-19 11:31 UTC, Dax0s approved these changes

2024-09-19 11:36 UTC, AiniusG approved these changes
LGTM

2024-09-19 11:36 UTC, AiniusG commented on frontend/src/ReactionButton.css
> +
Nežinau ar veikia format command ant css failu (lyg padariau, kad neveiktu, gal reiks pakeist) bet tarpus consistent laikyk jeigu juos darai. Taip pat su css trumpiniu geriau nedaryt, nes kitiem zmonem gali but sunkiau, o šiaip su naming viskas labai good.

2024-09-19 11:36 UTC, AiniusG commented on frontend/src/ReactionButton.tsx
> +  let reactionState = useRef(ReactionState.BASE);
Kiek žinau, gal klystų @Dax0s bet man atrodo reiktų labai stengtis nenaudot let, kadangi jų apibrėžimas yra įvairus, su const geriau būtų. Jeigu yra atvėjai kada reikia keist values, naudoji useState

2024-09-19 11:40 UTC, Dax0s commented on frontend/src/ReactionButton.tsx
> +  let reactionState = useRef(ReactionState.BASE);
Siaip yeah, ir cia butu galima tsg padaryti `const reactionState = useRef(ReactionState.BASE);`
Reiktu jauciu visur kur yra let pakeisti i const jeigu galima

2024-09-19 11:51 UTC, merged